name: publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup node 20 env
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: build
        run: |
          git config --global url."https://github.com/".insteadOf git://github.com/
          npm install
          npm run build

      - name: Install ossutil
        run: |
          curl -L https://gosspublic.alicdn.com/ossutil/1.7.14/ossutil64 -o /usr/local/bin/ossutil
          chmod +x /usr/local/bin/ossutil

      - name: Configure ossutil
        run: |
          ossutil config -e oss-${{ secrets.OSS_REGION }}.aliyuncs.com -i ${{ secrets.OSS_ACCESS_KEY_ID }} -k ${{ secrets.OSS_ACCESS_KEY_SECRET }} -L CH

      - name: Publish to OSS
        run: |
          if [ "${{ secrets.OSS_TARGET_PATH }}" = "." ]; then
            ossutil sync ./dist oss://${{ secrets.OSS_BUCKET }}/ --update
          else
            ossutil sync ./dist oss://${{ secrets.OSS_BUCKET }}/${{ secrets.OSS_TARGET_PATH }}/ --update
          fi
